[package]
name = "nats-util"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2"
serde = "1"
serde_json = "1.0.116"
bytes = "1.10"
async-nats.git = "https://github.com/nats-io/nats.rs"

[lints]
workspace = true
